{
  "openapi": "3.0.0",
  "info": {
    "title": "Atlas Documentation",
    "description": "This is a documentation Atlas API",
    "version": "1.0.0",
    "contact": {
      "email": "gusta.coliveira07@gmail.com"
    }
  },
  "paths": {
    "/users": {
      "post": {
        "tags": ["Users"],
        "summary": "Create a user",
        "description": "Create a new User",
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": { "type": "string" },
                  "email": { "type": "string" }
                }
              },
              "example": {
                "name": "Gustavo Oliveira",
                "email": "gusta@gamail.com"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "id": "e4cd94d7-7e13-4007-9e78-48ee7b0960c7",
                  "name": "Gustavo Oliveira",
                  "email": "gusta@gamail.com",
                  "admin": false,
                  "created_at": "2021-09-21T16:29:26.938Z",
                  "updated_at": "2021-09-21T16:29:26.938Z"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": { "type": "string" }
                  }
                },
                "example": {
                  "error": "This email is already in use"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Users"],
        "summary": "List all users",
        "description": "List all users in repository (Only admins)",
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "User id"
          }
        ],
        "responses": {
          "200": {
            "description": "Operation performed successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "$ref": "#/components/schemas/User"
                },
                "example": [
                  {
                    "id": "e4cd94d7-7e13-4007-9e78-48ee7b0960c7",
                    "name": "Gustavo Oliveira",
                    "email": "gusta@gamail.com",
                    "admin": false,
                    "created_at": "2021-09-21T16:29:26.938Z",
                    "updated_at": "2021-09-21T16:29:26.938Z"
                  },
                  {
                    "id": "e4cd94d7-7e13-4007-9e78-48ee7b0960c7",
                    "name": "Gustavo Oliveira",
                    "email": "gusta@gamail.com",
                    "admin": false,
                    "created_at": "2021-09-21T16:29:26.938Z",
                    "updated_at": "2021-09-21T16:29:26.938Z"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Permision denied",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": { "type": "string" }
                  }
                },
                "example": {
                  "error": "Permision denied"
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": ["Users"],
        "summary": "List a user by user_id",
        "description": "List a user by user_id",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "User id"
          }
        ],
        "responses": {
          "200": {
            "description": "Operation performed successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "$ref": "#/components/schemas/User"
                },
                "example": [
                  {
                    "id": "e4cd94d7-7e13-4007-9e78-48ee7b0960c7",
                    "name": "Gustavo Oliveira",
                    "email": "gusta@gamail.com",
                    "admin": false,
                    "created_at": "2021-09-21T16:29:26.938Z",
                    "updated_at": "2021-09-21T16:29:26.938Z"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": { "type": "string" }
                  }
                },
                "example": {
                  "error": "User not found"
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/admin": {
      "patch": {
        "tags": ["Users"],
        "summary": "Turn admin",
        "description": "Turn a user admin",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "User id"
          }
        ],
        "responses": {
          "200": {
            "description": "Operation performed successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "$ref": "#/components/schemas/User"
                },
                "example": [
                  {
                    "id": "e4cd94d7-7e13-4007-9e78-48ee7b0960c7",
                    "name": "Gustavo Oliveira",
                    "email": "gusta@gamail.com",
                    "admin": false,
                    "created_at": "2021-09-21T16:29:26.938Z",
                    "updated_at": "2021-09-21T16:29:26.938Z"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": { "type": "string" }
                  }
                },
                "example": {
                  "error": "User not found"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "name": { "type": "string" },
          "email": { "type": "string" },
          "admin": { "type": "boolean" },
          "created_at": { "type": "string", "format": "date-time" },
          "updated_at": { "type": "string", "format": "date-time" }
        }
      }
    },
    "securitySchemas": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
